# .readthedocs.yml — Corrected and Recommended Configuration
version: 2

# Specifies which version of your repository to build
checkout:
  version: main
  
# Specifies the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Specifies the Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
  # Set to true to fail on warnings once your build is stable
  fail_on_warning: false

# Defines the Python package installation steps
python:
  install:
    # Step 1: Install all documentation dependencies first.
    # This ensures all required packages are available.
    - requirements: docs/requirements.txt
    
    # Step 2: Install your project itself so Sphinx can import it.
    # The `extra_args` key is removed as it's invalid.
    - method: pip
      path: .
