# .readthedocs.yml — Read the Docs build configuration
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    # Install package so Sphinx can import it
    - method: pip
      path: . 
      extra_args: ["--upgrade", "--force-reinstall"]
      # first install your documentation dependencies
    - requirements: docs/requirements.txt
    
sphinx:
  configuration: docs/source/conf.py
  # make this true once things are stable, to catch warnings
  fail_on_warning: false
