# -*- coding: utf-8 -*-
# License: BSD-3-Clause
# Author: LKouadio

"""
Google Maps HTML template for GeoPrior map canvas.

Exposes the same __GeoPriorMap API used by ForecastMapView.
"""

from __future__ import annotations

import json
from typing import List


__all__ = ["google_html"]


def google_html(api_key: str) -> str:
    key = str(api_key or "").strip()

    # Note: keep API key out of logs if possible.
    api_src = (
        "https://maps.googleapis.com/maps/api/js"
        "?key=" + key +
        "&callback=__gp_initMap"
    )

    lines: List[str] = [
        "<!doctype html>",
        "<html>",
        "<head>",
        '<meta charset="utf-8"/>',
        '<meta name="viewport" '
        'content="width=device-width, initial-scale=1.0"/>',
        '<script src="qrc:///qtwebchannel/qwebchannel.js"></script>',
        "<style>",
        "  html, body { height: 100%; margin: 0; }",
        "  #map { height: 100%; width: 100%; }",
        "  .gp-legend {",
        "    position: absolute;",
        "    right: 12px;",
        "    bottom: 12px;",
        "    background: rgba(255,255,255,0.85);",
        "    padding: 8px;",
        "    border-radius: 10px;",
        "    font-family: sans-serif;",
        "    font-size: 12px;",
        "    pointer-events: none;",
        "    z-index: 10;",
        "  }",
        "</style>",
        "</head>",
        "<body>",
        '<div id="map"></div>',
        "<script>",
        "(function () {",
        "  // Stub API (Google loads async) + cache last calls",
        "  let bridge = null;",
        "  function _emitPointClicked(x, y) {",
        "    if (bridge && bridge.pointClicked) {",
        "      bridge.pointClicked(x, y);",
        "    }",
        "  }",
        "  if (typeof QWebChannel !== 'undefined' &&",
        "      typeof qt !== 'undefined' &&",
        "      qt.webChannelTransport) {",
        "    new QWebChannel(",
        "      qt.webChannelTransport,",
        "      function (channel) {",
        "        bridge = channel.objects.bridge || null;",
        "      }",
        "    );",
        "  }",
        "",
        "  let gMap = null;",
        "  let gData = null;",
        "  let legendEl = null;",
        "",
        "  let lastPoints = null;",
        "  let lastPointOpts = null;",
        "  let lastHotspots = null;",
        "  let lastHotOpts = null;",
        "",
        "  // Hot overlays",
        "  let hotCores = [];",
        "  let hotRings = [];",
        "  let hotTimers = [];",
        "",
        "  function _stopHotTimers() {",
        "    for (let i = 0; i < hotTimers.length; i++) {",
        "      try { clearInterval(hotTimers[i]); } catch (e) {}",
        "    }",
        "    hotTimers = [];",
        "  }",
        "",
        "  function _clearData() {",
        "    if (!gData) return;",
        "    const rm = [];",
        "    gData.forEach(function (f) { rm.push(f); });",
        "    for (let i = 0; i < rm.length; i++) gData.remove(rm[i]);",
        "  }",
        "",
        "  function _clamp(x, a, b) {",
        "    return Math.max(a, Math.min(b, x));",
        "  }",
        "",
        "  function _color(t, cmap, inv) {",
        "    let tt = t;",
        "    if (inv) tt = 1 - tt;",
        "    const h = 240 * (1 - tt);",
        "    return 'hsl(' + h + ',80%,45%)';",
        "  }",
        "",
        "  function setLegend(vmin, vmax, label, cmap, inv) {",
        "    if (legendEl && legendEl.parentNode) {",
        "      try { legendEl.parentNode.removeChild(legendEl); }",
        "      catch (e) {}",
        "    }",
        "    const cm = cmap || 'viridis';",
        "    const iv = !!inv;",
        "    const title = (label || 'Z');",
        "    const g = (",
        "      'linear-gradient(to top,' +",
        "      _color(0, cm, iv) + ',' +",
        "      _color(1, cm, iv) + ')'",
        "    );",
        "    const div = document.createElement('div');",
        "    div.className = 'gp-legend';",
        "    div.innerHTML = (",
        "      '<div style=\"font-weight:600;\">' + title + '</div>' +",
        "      '<div style=\"display:flex;gap:8px;align-items:center;\">' +",
        "      '<div style=\"width:12px;height:90px;background:' + g +",
        "      ';border-radius:6px;\"></div>' +",
        "      '<div>' +",
        "      '<div>' + Number(vmax).toFixed(3) + '</div>' +",
        "      '<div style=\"height:62px;\"></div>' +",
        "      '<div>' + Number(vmin).toFixed(3) + '</div>' +",
        "      '</div></div>'",
        "    );",
        "    document.body.appendChild(div);",
        "    legendEl = div;",
        "  }",
        "",
        "  function clearPoints() {",
        "    lastPoints = null;",
        "    lastPointOpts = null;",
        "    _clearData();",
        "  }",
        "",
        "  function setPoints(points, opts) {",
        "    lastPoints = points || [];",
        "    lastPointOpts = opts || {};",
        "",
        "    if (!gData) return; // not ready yet",
        "    _clearData();",
        "",
        "    const p = lastPoints;",
        "    const o = lastPointOpts;",
        "",
        "    const r = (o.radius != null) ? Number(o.radius) : 6;",
        "    const op = (o.opacity != null) ? Number(o.opacity) : 0.9;",
        "    const vmin = (o.vmin != null) ? Number(o.vmin) : null;",
        "    const vmax = (o.vmax != null) ? Number(o.vmax) : null;",
        "    const cmap = o.cmap || 'viridis';",
        "    const inv = !!o.invert;",
        "",
        "    let lo = Infinity;",
        "    let hi = -Infinity;",
        "    for (let i = 0; i < p.length; i++) {",
        "      const vv = p[i].v;",
        "      if (vv == null || !isFinite(vv)) continue;",
        "      lo = Math.min(lo, vv);",
        "      hi = Math.max(hi, vv);",
        "    }",
        "    const a = (vmin != null) ? vmin : lo;",
        "    const b = (vmax != null) ? vmax : hi;",
        "",
        "    // Add as GeoJSON features via Data layer",
        "    const fc = { type: 'FeatureCollection', features: [] };",
        "    for (let i = 0; i < p.length; i++) {",
        "      const pt = p[i];",
        "      const lat = Number(pt.lat);",
        "      const lon = Number(pt.lon);",
        "      const vv = pt.v;",
        "      if (!isFinite(lat) || !isFinite(lon)) continue;",
        "",
        "      let t = 0.5;",
        "      if (vv != null && isFinite(vv) && b > a) {",
        "        t = (vv - a) / (b - a);",
        "      }",
        "      t = _clamp(t, 0, 1);",
        "      const col = _color(t, cmap, inv);",
        "",
        "      fc.features.push({",
        "        type: 'Feature',",
        "        geometry: {",
        "          type: 'Point',",
        "          coordinates: [lon, lat]",
        "        },",
        "        properties: { col: col }",
        "      });",
        "    }",
        "",
        "    gData.addGeoJson(fc);",
        "",
        "    gData.setStyle(function (feature) {",
        "      const col = feature.getProperty('col') || '#3f88c5';",
        "      return {",
        "        icon: {",
        "          path: google.maps.SymbolPath.CIRCLE,",
        "          fillColor: col,",
        "          fillOpacity: op,",
        "          strokeColor: col,",
        "          strokeOpacity: op,",
        "          strokeWeight: 1,",
        "          scale: r",
        "        }",
        "      };",
        "    });",
        "",
        "    if (o.showLegend) {",
        "      setLegend(a, b, o.label || 'Z', cmap, inv);",
        "    }",
        "  }",
        "",
        "  function fitPoints() {",
        "    if (!gMap) return;",
        "    const pts = [];",
        "    const p = lastPoints || [];",
        "    for (let i = 0; i < p.length; i++) {",
        "      const lat = Number(p[i].lat);",
        "      const lon = Number(p[i].lon);",
        "      if (!isFinite(lat) || !isFinite(lon)) continue;",
        "      pts.push(new google.maps.LatLng(lat, lon));",
        "    }",
        "    const h = lastHotspots || [];",
        "    for (let i = 0; i < h.length; i++) {",
        "      const lat = Number(h[i].lat);",
        "      const lon = Number(h[i].lon);",
        "      if (!isFinite(lat) || !isFinite(lon)) continue;",
        "      pts.push(new google.maps.LatLng(lat, lon));",
        "    }",
        "    if (!pts.length) return;",
        "",
        "    const b = new google.maps.LatLngBounds();",
        "    for (let i = 0; i < pts.length; i++) b.extend(pts[i]);",
        "    gMap.fitBounds(b);",
        "  }",
        "",
        "  function zoomIn() { if (gMap) gMap.setZoom(gMap.getZoom() + 1); }",
        "  function zoomOut(){ if (gMap) gMap.setZoom(gMap.getZoom() - 1); }",
        "",
        "  function setBasemap(provider, style, opacity) {",
        "    if (!gMap) return;",
        "    const p = String(provider || 'streets').toLowerCase();",
        "    const s = String(style || 'light').toLowerCase();",
        "",
        "    // mapTypeId mapping",
        "    let mt = 'roadmap';",
        "    if (p === 'satellite') mt = 'satellite';",
        "    if (p === 'terrain') mt = 'terrain';",
        "    if (p === 'hybrid') mt = 'hybrid';",
        "    gMap.setMapTypeId(mt);",
        "",
        "    // optional dark style (minimal)",
        "    if (s === 'dark') {",
        "      gMap.setOptions({ styles: [",
        "        { elementType: 'geometry', stylers: [{ lightness: -35 }] },",
        "        { elementType: 'labels.text.fill', stylers: [{ lightness: 20 }] },",
        "        { elementType: 'labels.text.stroke', stylers: [{ lightness: -40 }] }",
        "      ]});",
        "    } else {",
        "      gMap.setOptions({ styles: null });",
        "    }",
        "",
        "    // opacity ignored for base map (API limitation).",
        "    void(opacity);",
        "  }",
        "",
        "  function showHotspots(on) {",
        "    const v = !!on;",
        "    for (let i = 0; i < hotCores.length; i++) {",
        "      hotCores[i].setMap(v ? gMap : null);",
        "    }",
        "    for (let i = 0; i < hotRings.length; i++) {",
        "      hotRings[i].setMap(v ? gMap : null);",
        "    }",
        "  }",
        "",
        "  function clearHotspots() {",
        "    _stopHotTimers();",
        "    for (let i = 0; i < hotCores.length; i++) hotCores[i].setMap(null);",
        "    for (let i = 0; i < hotRings.length; i++) hotRings[i].setMap(null);",
        "    hotCores = [];",
        "    hotRings = [];",
        "    lastHotspots = null;",
        "    lastHotOpts = null;",
        "  }",
        "",
        "  function _sevColor(sev) {",
        "    const s = (sev || 'high').toLowerCase();",
        "    if (s === 'critical') return '#d7263d';",
        "    if (s === 'high') return '#f18f01';",
        "    if (s === 'medium') return '#3f88c5';",
        "    return '#6c757d';",
        "  }",
        "",
        "  function setHotspots(hs, opts) {",
        "    clearHotspots();",
        "    lastHotspots = hs || [];",
        "    lastHotOpts = opts || {};",
        "    if (!gMap) return;",
        "",
        "    const h = lastHotspots;",
        "    const o = lastHotOpts;",
        "",
        "    const want = (o.show != null) ? !!o.show : true;",
        "    const style = String(o.style || 'pulse').toLowerCase();",
        "    const pulse = (o.pulse != null) ? !!o.pulse : true;",
        "",
        "    let ringKm = Number(o.ringKm);",
        "    if (!isFinite(ringKm) || ringKm <= 0) ringKm = 0.8;",
        "    const r0m = ringKm * 1000.0;",
        "",
        "    let sp = Number(o.pulseSpeed);",
        "    if (!isFinite(sp) || sp <= 0) sp = 1.0;",
        "    let dt = 80 / sp;",
        "    dt = Math.max(25, Math.min(200, dt));",
        "",
        "    for (let i = 0; i < h.length; i++) {",
        "      const pt = h[i] || {};",
        "      const lat = Number(pt.lat);",
        "      const lon = Number(pt.lon);",
        "      if (!isFinite(lat) || !isFinite(lon)) continue;",
        "",
        "      const col = _sevColor(pt.sev || 'high');",
        "",
        "      const core = new google.maps.Marker({",
        "        position: { lat: lat, lng: lon },",
        "        map: want ? gMap : null,",
        "        icon: {",
        "          path: google.maps.SymbolPath.CIRCLE,",
        "          fillColor: col,",
        "          fillOpacity: 0.95,",
        "          strokeColor: col,",
        "          strokeWeight: 1,",
        "          scale: 5",
        "        }",
        "      });",
        "      core.addListener('click', function () {",
        "        _emitPointClicked(lon, lat);",
        "      });",
        "      hotCores.push(core);",
        "",
        "      const ring = new google.maps.Circle({",
        "        center: { lat: lat, lng: lon },",
        "        radius: r0m,",
        "        map: want ? gMap : null,",
        "        strokeColor: col,",
        "        strokeOpacity: (style === 'glow') ? 0.55 : 0.9,",
        "        strokeWeight: 2,",
        "        fillOpacity: 0.0",
        "      });",
        "      hotRings.push(ring);",
        "",
        "      if (style !== 'glow' && pulse) {",
        "        let rr = r0m;",
        "        let aa = 0.9;",
        "        const t = setInterval(function () {",
        "          rr += (r0m * 0.06);",
        "          aa -= 0.04;",
        "          if (aa <= 0.05) {",
        "            rr = r0m;",
        "            aa = 0.9;",
        "          }",
        "          try {",
        "            ring.setRadius(rr);",
        "            ring.setOptions({ strokeOpacity: aa });",
        "          } catch (e) {}",
        "        }, dt);",
        "        hotTimers.push(t);",
        "      }",
        "    }",
        "  }",
        "",
        "  // Google callback (async)",
        "  window.__gp_initMap = function () {",
        "    gMap = new google.maps.Map(",
        "      document.getElementById('map'),",
        "      { center: { lat: 0, lng: 0 }, zoom: 2 }",
        "    );",
        "",
        "    gData = new google.maps.Data({ map: gMap });",
        "",
        "    // Click on features",
        "    gData.addListener('click', function (e) {",
        "      try {",
        "        const ll = e.latLng;",
        "        _emitPointClicked(ll.lng(), ll.lat());",
        "      } catch (err) {}",
        "    });",
        "",
        "    // Map click background",
        "    gMap.addListener('click', function (e) {",
        "      if (!e || !e.latLng) return;",
        "      _emitPointClicked(e.latLng.lng(), e.latLng.lat());",
        "    });",
        "",
        "    // Apply cached state if any",
        "    if (lastPointOpts && lastPoints) {",
        "      setPoints(lastPoints, lastPointOpts);",
        "    }",
        "    if (lastHotOpts && lastHotspots) {",
        "      setHotspots(lastHotspots, lastHotOpts);",
        "    }",
        "  };",
        "",
        "  // Attach API functions",
        "  window.__GeoPriorMap.setPoints = setPoints;",
        "  window.__GeoPriorMap.clearPoints = clearPoints;",
        "  window.__GeoPriorMap.fitPoints = fitPoints;",
        "  window.__GeoPriorMap.zoomIn = zoomIn;",
        "  window.__GeoPriorMap.zoomOut = zoomOut;",
        "  window.__GeoPriorMap.setLegend = setLegend;",
        "  window.__GeoPriorMap.setBasemap = setBasemap;",
        "  window.__GeoPriorMap.setHotspots = setHotspots;",
        "  window.__GeoPriorMap.clearHotspots = clearHotspots;",
        "  window.__GeoPriorMap.showHotspots = showHotspots;",
        "})();",
        "</script>",
        f'<script src="{api_src}" async defer></script>',
        "</body>",
        "</html>",
    ]
    return "\n".join(lines)
