
from __future__ import annotations

def _leaflet_html() -> str:
    lines = [
        "<!doctype html>",
        "<html>",
        "<head>",
        '<meta charset="utf-8"/>',
        '<meta name="viewport"',
        'content="width=device-width, initial-scale=1.0"/>',
        '<link rel="stylesheet"',
        'href="https://unpkg.com/leaflet@1.9.4/'
        'dist/leaflet.css"/>',
        "<script",
        'src="https://unpkg.com/leaflet@1.9.4/'
        'dist/leaflet.js"></script>',
        '<script src="qrc:///qtwebchannel/'
        'qwebchannel.js"></script>',
        "<style>",
        "  html, body { height: 100%; margin: 0; }",
        "  #map { height: 100%; width: 100%; }",
        "</style>",
        "</head>",
        "<body>",
        '<div id="map"></div>',
        "<script>",
        "(function () {",
        "  // Define API first (safe if Leaflet fails)",
        "  window.__GeoPriorMap = {",
        "    setPoints: function(){},",
        "    clearPoints: function(){},",
        "    fitPoints: function(){},",
        "    zoomIn: function(){},",
        "    zoomOut: function(){},",
        "    setLegend: function(){},",
        "    setBasemap: function(){},",
        "    setHotspots: function(){},",
        "    clearHotspots: function(){},",
        "    showHotspots: function(){}",
        "  };",
        "",
        "  if (typeof L === 'undefined') {",
        "    console.log('Leaflet not available.');",
        "    return;",
        "  }",
        "",
        "  const map = L.map('map', {",
        "    zoomControl: true",
        "  }).setView([0, 0], 2);",
        "",
        "  // Remove only the Leaflet prefix, keep provider attribution",
        "  map.attributionControl.setPrefix('');",
        "",
        "  const osmUrl = (",
        "    'https://{s}.tile.openstreetmap.org/' +",
        "    '{z}/{x}/{y}.png'",
        "  );",
        "  const osmAtt = '© OpenStreetMap';",
        "",
        "  // Track tile layer so we can swap basemaps",
        "  let tileLayer = L.tileLayer(osmUrl, {",
        "    maxZoom: 19,",
        "    attribution: osmAtt",
        "  }).addTo(map);",
        "",
        "  const layer = L.layerGroup().addTo(map);",
        "  let legendCtl = null;",
        "",
        "  // Qt WebChannel bridge (JS -> Python)",
        "  let bridge = null;",
        "",
        "  // Hotspots layer (separate from points)",
        "  const hotLayer = L.layerGroup().addTo(map);",
        "  let hotOn = true;",
        "  let hotTimers = [];",
        "",
        "  function _stopHotTimers() {",
        "    for (let i = 0; i < hotTimers.length; i++) {",
        "      try { clearInterval(hotTimers[i]); }",
        "      catch (e) {}",
        "    }",
        "    hotTimers = [];",
        "  }",
        "",
        "  function clearHotspots() {",
        "    _stopHotTimers();",
        "    hotLayer.clearLayers();",
        "  }",
        "",
        "  function _sevColor(sev) {",
        "    const s = (sev || 'high').toLowerCase();",
        "    if (s === 'critical') return '#d7263d';",
        "    if (s === 'high') return '#f18f01';",
        "    if (s === 'medium') return '#3f88c5';",
        "    return '#6c757d';",
        "  }",
        "",
        "  function _sevRadius(sev) {",
        "    const s = (sev || 'high').toLowerCase();",
        "    if (s === 'critical') return 18;",
        "    if (s === 'high') return 14;",
        "    if (s === 'medium') return 12;",
        "    return 10;",
        "  }",
        "",
        "  function _pulseRing(ring, r0m, speed) {",
        "    let r = r0m;",
        "    let a = 0.9;",
        "",
        "    let sp = Number(speed);",
        "    if (!isFinite(sp) || sp <= 0) sp = 1.0;",
        "",
        "    // Faster speed -> smaller dt",
        "    let dt = 80 / sp;",
        "    dt = Math.max(25, Math.min(200, dt));",
        "",
        "    const t = setInterval(function () {",
        "      r += (r0m * 0.06);",
        "      a -= 0.04;",
        "",
        "      if (a <= 0.05) {",
        "        r = r0m;",
        "        a = 0.9;",
        "      }",
        "",
        "      try {",
        "        ring.setRadius(r);",
        "        ring.setStyle({ opacity: a });",
        "      } catch (e) {}",
        "    }, dt);",
        "",
        "    hotTimers.push(t);",
        "  }",
        "",
        "  function showHotspots(on) {",
        "    hotOn = !!on;",
        "    if (hotOn) map.addLayer(hotLayer);",
        "    else map.removeLayer(hotLayer);",
        "  }",
        "",
        "  function _emitPointClicked(x, y) {",
        "    if (bridge && bridge.pointClicked) {",
        "      bridge.pointClicked(x, y);",
        "    }",
        "  }",
        "",
        "  if (typeof QWebChannel !== 'undefined' &&",
        "      typeof qt !== 'undefined' &&",
        "      qt.webChannelTransport) {",
        "    new QWebChannel(",
        "      qt.webChannelTransport,",
        "      function (channel) {",
        "        bridge = channel.objects.bridge || null;",
        "      }",
        "    );",
        "  }",
        "",
        "  // Optional: clicking map background also selects",
        "  map.on('click', function (e) {",
        "    if (!e || !e.latlng) return;",
        "    _emitPointClicked(e.latlng.lng, e.latlng.lat);",
        "  });",

        "  function clearPoints() {",
        "    layer.clearLayers();",
        "  }",
        "",
        "  function _clamp(x, a, b) {",
        "    return Math.max(a, Math.min(b, x));",
        "  }",
        "",
        "  function _color(t, cmap, inv) {",
        "    let tt = t;",
        "    if (inv) tt = 1 - tt;",
        "    // v0: keep HSL fallback (cmap reserved)",
        "    const h = 240 * (1 - tt);",
        "    return 'hsl(' + h + ',80%,45%)';",
        "  }",
        "",
        "  function _normBasemapArgs(provider, style, opacity) {",
        "    let p0 = provider;",
        "    let s0 = style;",
        "    let o0 = opacity;",
        "    // Allow passing a single object: {p/s/o} or {provider/style/opacity}",
        "    if (p0 && (typeof p0 === 'object')) {",
        "      o0 = (p0.o != null) ? p0.o : ((p0.opacity != null) ? p0.opacity : o0);",
        "      s0 = (p0.s != null) ? p0.s : ((p0.style != null) ? p0.style : s0);",
        "      p0 = (p0.p != null) ? p0.p : ((p0.provider != null) ? p0.provider : p0.key);",
        "    }",
        "    const p = String(p0 || 'osm').toLowerCase();",
        "    const s = String(s0 || 'light').toLowerCase();",
        "    const o = (o0 != null) ? Number(o0) : 1.0;",
        "    return { p: p, s: s, o: o };",
        "  }",
        "",
        "  function setBasemap(provider, style, opacity) {",
        "    const a = _normBasemapArgs(provider, style, opacity);",
        "    const p = a.p;",
        "    const s = a.s;",
        "",
        "    let url = osmUrl;",
        "    let att = osmAtt;",
        "    let sub = 'abc';",
        "    let maxZ = 19;",
        "",
        "    if (p === 'osm' && s === 'dark') {",
        "      url = (",
        "        'https://{s}.basemaps.cartocdn.com/' +",
        "        'dark_all/{z}/{x}/{y}{r}.png'",
        "      );",
        "      att = '© OpenStreetMap © CARTO';",
        "      sub = 'abcd';",
        "      maxZ = 19;",
        "    } else if (p === 'osm' && s === 'gray') {",
        "      url = (",
        "        'https://{s}.basemaps.cartocdn.com/' +",
        "        'light_all/{z}/{x}/{y}{r}.png'",
        "      );",
        "      att = '© OpenStreetMap © CARTO';",
        "      sub = 'abcd';",
        "      maxZ = 19;",
        "    } else if (p === 'terrain') {",
        "      url = 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png';",
        "      att = '© OpenStreetMap © OpenTopoMap';",
        "      sub = 'abc';",
        "      maxZ = 17;",
        "    } else if (p === 'satellite') {",
        "      url = (",
        "        'https://server.arcgisonline.com/' +",
        "        'ArcGIS/rest/services/World_Imagery/' +",
        "        'MapServer/tile/{z}/{y}/{x}'",
        "      );",
        "      att = 'Tiles © Esri';",
        "      sub = '';",
        "      maxZ = 19;",
        "    }",
        "",
        "    const op = (isFinite(a.o)) ? a.o : 1.0;",
        "",
        "    if (tileLayer) {",
        "      map.removeLayer(tileLayer);",
        "      tileLayer = null;",
        "    }",
        "",
        "    tileLayer = L.tileLayer(url, {",
        "      maxZoom: maxZ,",
        "      attribution: att,",
        "      opacity: op,",
        "      subdomains: sub",
        "    }).addTo(map);",
        "  }",
        "",
        "  function setLegend(vmin, vmax, label, cmap, inv) {",
        "    if (legendCtl) {",
        "      map.removeControl(legendCtl);",
        "      legendCtl = null;",
        "    }",
        "",
        "    const cm = cmap || 'viridis';",
        "    const iv = !!inv;",
        "",
        "    legendCtl = L.control({ position: 'bottomright' });",
        "    legendCtl.onAdd = function() {",
        "      const div = L.DomUtil.create('div');",
        "      div.style.background = 'rgba(255,255,255,0.85)';",
        "      div.style.padding = '8px';",
        "      div.style.borderRadius = '10px';",
        "      div.style.fontFamily = 'sans-serif';",
        "      div.style.fontSize = '12px';",
        "",
        "      const title = (label || 'Z');",
        "      const g = (",
        "        'linear-gradient(to top,' +",
        "        _color(0, cm, iv) + ',' +",
        "        _color(1, cm, iv) + ')'",
        "      );",
        "",
        "      div.innerHTML = (",
        "        '<div style=\"font-weight:600;\">' +",
        "        title + '</div>' +",
        "        '<div style=\"display:flex;gap:8px;' +",
        "        'align-items:center;\">' +",
        "        '<div style=\"width:12px;height:90px;' +",
        "        'background:' + g + ';border-radius:6px;\">' +",
        "        '</div>' +",
        "        '<div>' +",
        "        '<div>' + Number(vmax).toFixed(3) + '</div>' +",
        "        '<div style=\"height:62px;\"></div>' +",
        "        '<div>' + Number(vmin).toFixed(3) + '</div>' +",
        "        '</div></div>'",
        "      );",
        "",
        "      return div;",
        "    };",
        "    legendCtl.addTo(map);",
        "  }",
        "",
        "  function setPoints(points, opts) {",
        "    clearPoints();",
        "    const p = points || [];",
        "    const o = opts || {};",
        "",
        "    const r = (o.radius != null) ? o.radius : 6;",
        "    const op = (o.opacity != null) ? o.opacity : 0.9;",
        "    const vmin = (o.vmin != null) ? o.vmin : null;",
        "    const vmax = (o.vmax != null) ? o.vmax : null;",
        "",
        "    const cmap = o.cmap || 'viridis';",
        "    const inv = !!o.invert;",
        "",
        "    let lo = Infinity;",
        "    let hi = -Infinity;",
        "",
        "    for (let i = 0; i < p.length; i++) {",
        "      const v = p[i].v;",
        "      if (v == null || !isFinite(v)) continue;",
        "      lo = Math.min(lo, v);",
        "      hi = Math.max(hi, v);",
        "    }",
        "",
        "    const a = (vmin != null) ? vmin : lo;",
        "    const b = (vmax != null) ? vmax : hi;",
        "",
        "    for (let i = 0; i < p.length; i++) {",
        "      const pt = p[i];",
        "      const lat = pt.lat;",
        "      const lon = pt.lon;",
        "      const v = pt.v;",
        "      if (!isFinite(lat) || !isFinite(lon)) continue;",
        "",
        "      let t = 0.5;",
        "      if (v != null && isFinite(v) && b > a) {",
        "        t = (v - a) / (b - a);",
        "      }",
        "      t = _clamp(t, 0, 1);",
        "      const col = _color(t, cmap, inv);",
        "",
        "      const m = L.circleMarker([lat, lon], {",
        "        radius: r,",
        "        color: col,",
        "        fillColor: col,",
        "        fillOpacity: op,",
        "        weight: 1",
        "      }).addTo(layer);",
        "",
        "      // Emit (x,y) as (lon,lat) to match X/Y columns",
        "      m.on('click', function () {",
        "        _emitPointClicked(lon, lat);",
        "      });",
        "    }",
        "",
        "    if (o.showLegend) {",
        "      setLegend(a, b, o.label || 'Z', cmap, inv);",
        "    }",
        "  }",
        "",
        "  function setHotspots(hs, opts) {",
        "    clearHotspots();",
        "",
        "    const h = hs || [];",
        "    const o = opts || {};",
        "",
        "    const want = (o.show != null) ? !!o.show : true;",
        "    showHotspots(want);",
        "",
        "    const style = String(o.style || 'pulse').toLowerCase();",
        "    const pulse = (o.pulse != null) ? !!o.pulse : true;",
        "    const labels = (o.labels != null) ? !!o.labels : true;",
        "",
        "    let baseKm = Number(o.ringKm);",
        "    if (!isFinite(baseKm) || baseKm <= 0) baseKm = 0.8;",
        "",
        "    let sp = Number(o.pulseSpeed);",
        "    if (!isFinite(sp) || sp <= 0) sp = 1.0;",
        "",
        "    function _sevMul(sev) {",
        "      const s = (sev || 'high').toLowerCase();",
        "      if (s === 'critical') return 1.6;",
        "      if (s === 'high') return 1.25;",
        "      if (s === 'medium') return 1.0;",
        "      return 0.8;",
        "    }",
        "",
        "    for (let i = 0; i < h.length; i++) {",
        "      const pt = h[i] || {};",
        "      const lat = pt.lat;",
        "      const lon = pt.lon;",
        "      if (!isFinite(lat) || !isFinite(lon)) continue;",
        "",
        "      const sev = pt.sev || 'high';",
        "      const col = _sevColor(sev);",
        "      const mul = _sevMul(sev);",
        "",
        "      const tip = pt.label || ('Hotspot #' + (i + 1));",
        "",
        "      const core = L.circleMarker([lat, lon], {",
        "        radius: 5,",
        "        color: col,",
        "        fillColor: col,",
        "        fillOpacity: 0.95,",
        "        weight: 1",
        "      }).addTo(hotLayer);",
        "",
        "      if (labels) core.bindTooltip(tip);",
        "      core.on('click', function () {",
        "        _emitPointClicked(lon, lat);",
        "      });",
        "",
        "      // Style layer",
        "      if (style === 'glow') {",
        "        const glow = L.circle([lat, lon], {",
        "          radius: (baseKm * 1000.0 * mul),",
        "          color: col,",
        "          opacity: 0.55,",
        "          fillColor: col,",
        "          fillOpacity: 0.12,",
        "          weight: 1",
        "        }).addTo(hotLayer);",
        "        if (labels) glow.bindTooltip(tip);",
        "        glow.on('click', function () {",
        "          _emitPointClicked(lon, lat);",
        "        });",
        "        continue;",
        "      }",
        "",
        "      // Pulse ring (meters-based)",
        "      const r0m = (baseKm * 1000.0 * mul);",
        "      const ring = L.circle([lat, lon], {",
        "        radius: r0m,",
        "        color: col,",
        "        opacity: 0.9,",
        "        fillOpacity: 0.0,",
        "        weight: 2",
        "      }).addTo(hotLayer);",
        "",
        "      if (labels) ring.bindTooltip(tip);",
        "      ring.on('click', function () {",
        "        _emitPointClicked(lon, lat);",
        "      });",
        "",
        "      if (pulse) _pulseRing(ring, r0m, sp);",
        "    }",
        "  }",
        "",
        "  function fitPoints() {",
        "    const pts = [];",
        "",
        "    layer.eachLayer(function (m) {",
        "      if (m.getLatLng) pts.push(m.getLatLng());",
        "    });",
        "",
        "    hotLayer.eachLayer(function (m) {",
        "      if (m.getLatLng) pts.push(m.getLatLng());",
        "      if (m.getBounds) {",
        "        try {",
        "          const b = m.getBounds();",
        "          pts.push(b.getNorthWest());",
        "          pts.push(b.getSouthEast());",
        "        } catch (e) {}",
        "      }",
        "    });",
        "",
        "    if (!pts.length) return;",
        "    map.fitBounds(L.latLngBounds(pts).pad(0.2));",
        "  }",
        "",
        "  function zoomIn() { map.zoomIn(); }",
        "  function zoomOut() { map.zoomOut(); }",
        "",
        "  // Attach real functions",
        "  window.__GeoPriorMap.setPoints = setPoints;",
        "  window.__GeoPriorMap.clearPoints = clearPoints;",
        "  window.__GeoPriorMap.fitPoints = fitPoints;",
        "  window.__GeoPriorMap.zoomIn = zoomIn;",
        "  window.__GeoPriorMap.zoomOut = zoomOut;",
        "  window.__GeoPriorMap.setLegend = setLegend;",
        "  window.__GeoPriorMap.setBasemap = setBasemap;",
        "  window.__GeoPriorMap.setHotspots = setHotspots;",
        "  window.__GeoPriorMap.clearHotspots = clearHotspots;",
        "  window.__GeoPriorMap.showHotspots = showHotspots;",
        "})();",
        "</script>",
        "</body>",
        "</html>",
    ]
    return "\n".join(lines)